### ISSUE TITLE
作者不好意思打扰一下

### ISSUE THREAD

**Issue by qq376526901** [yingshaoxo/E_Python#1]
用易语言运行之后显示要管理员才能运行
编译成文件给管理员权限了也还是提示需要管理员权限才能运行
这个问题如何处理

**Comment by yingshaoxo** [comment]
你可以在一开始就以管理员权限运行易语言

**Comment by yingshaoxo** [comment]
还有就是，你如果把运行路径改为非系统盘

就不需要给管理员权限(这个是win10的锅)

**Comment by yingshaoxo** [comment]
根据最新的反馈

请在安装Python时保持默认路径 （该错误源于win10的权限管理机制）
